# Generated by Django 3.1 on 2020-12-10 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queanswer',
            name='que',
        ),
        migrations.RemoveField(
            model_name='question',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='que_answer',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='user',
        ),
        migrations.DeleteModel(
            name='Poll',
        ),
        migrations.DeleteModel(
            name='QueAnswer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='UserAnswer',
        ),
    ]
