# Generated by Django 3.1 on 2020-12-10 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0002_auto_20201210_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('poll_id', models.AutoField(primary_key=True, serialize=False)),
                ('poll_title', models.CharField(max_length=128, verbose_name='Название опроса')),
                ('poll_desc', models.TextField(verbose_name='Описание опроса')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата старта')),
                ('answered_ad', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('que_id', models.AutoField(primary_key=True, serialize=False)),
                ('que_type', models.CharField(choices=[('text', 'Text answer'), ('one', 'One answer'), ('many', 'Many answers')], max_length=4)),
                ('que_title', models.CharField(max_length=128, verbose_name='Вопрос')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.poll', verbose_name='Опрос')),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que_answer', models.CharField(max_length=128, verbose_name='Ответ на вопрос')),
                ('que', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question', verbose_name='Вопрос')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='QueAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que_answer', models.CharField(max_length=128, verbose_name='Ответ на вопрос')),
                ('que', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question', verbose_name='Вопрос')),
            ],
        ),
    ]
