# Generated by Django 3.1 on 2020-12-10 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0003_poll_queanswer_question_useranswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='que',
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='que_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.queanswer', verbose_name='Ответ на вопрос'),
        ),
        migrations.CreateModel(
            name='UserTextAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que_textanswer', models.CharField(max_length=128, verbose_name='Текстовый ответ на вопрос')),
                ('que', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question', verbose_name='Вопрос')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
