# Generated by Django 3.1 on 2020-12-10 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0005_auto_20201210_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('poll_id', models.AutoField(primary_key=True, serialize=False)),
                ('poll_title', models.CharField(max_length=128, verbose_name='Название опроса')),
                ('poll_desc', models.TextField(verbose_name='Описание опроса')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата старта')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
            },
        ),
        migrations.CreateModel(
            name='QueAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que_answer', models.CharField(max_length=128, verbose_name='Ответ на вопрос')),
            ],
            options={
                'verbose_name': 'Ответ на вопрос',
                'verbose_name_plural': 'Ответы на вопросы',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('que_id', models.AutoField(primary_key=True, serialize=False)),
                ('que_type', models.CharField(choices=[('text', 'Ответ текстом'), ('one', 'Ответ с выбором одного варианта'), ('many', 'Ответ с выбором нескольких вариантов')], max_length=4, verbose_name='Тип вопроса')),
                ('que_title', models.CharField(max_length=128, verbose_name='Вопрос')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.poll', verbose_name='Опрос')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='UserTextAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que_textanswer', models.CharField(max_length=128, verbose_name='Текстовый ответ на вопрос')),
                ('que', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question', verbose_name='Вопрос')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Тестовый ответ пользователя',
                'verbose_name_plural': 'Текстовые ответы пользователей',
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.queanswer', verbose_name='Ответ на вопрос')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ответ пользователя',
                'verbose_name_plural': 'Ответы пользователей',
            },
        ),
        migrations.AddField(
            model_name='queanswer',
            name='que',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question', verbose_name='Вопрос'),
        ),
    ]
