# Generated by Django 3.1 on 2020-12-11 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20201210_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queanswer',
            name='que',
        ),
        migrations.RemoveField(
            model_name='question',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='que_answer',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usertextanswer',
            name='que',
        ),
        migrations.RemoveField(
            model_name='usertextanswer',
            name='user',
        ),
        migrations.DeleteModel(
            name='Poll',
        ),
        migrations.DeleteModel(
            name='QueAnswer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='UserAnswer',
        ),
        migrations.DeleteModel(
            name='UserTextAnswer',
        ),
    ]
